import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('templates').del();

  await knex('templates').insert([
    {
      name_en: 'Residential Development',
      name_es: 'Desarrollo Residencial',
      project_type: 'residential',
      description_en: 'Single-family homes or residential condominiums. Typical for suburban developments in Mexican cities.',
      description_es: 'Casas unifamiliares o condominios residenciales. Típico para desarrollos suburbanos en ciudades mexicanas.',
      default_costs: JSON.stringify([
        { category: 'land', subcategory: 'acquisition', description_en: 'Land acquisition', description_es: 'Adquisición de terreno', typical_pct: 20, typical_range_mxn: [5000000, 30000000] },
        { category: 'land', subcategory: 'notary', description_en: 'Notary fees (5-8% of land value)', description_es: 'Gastos notariales (5-8% del valor del terreno)', typical_pct: 1.5, typical_range_mxn: [250000, 2400000] },
        { category: 'taxes', subcategory: 'isai', description_en: 'Property acquisition tax (ISAI, 2-5%)', description_es: 'Impuesto sobre adquisición de inmuebles (ISAI, 2-5%)', typical_pct: 1, typical_range_mxn: [100000, 1500000] },
        { category: 'construction', subcategory: 'hard_costs', description_en: 'Construction hard costs ($8,000-15,000/m²)', description_es: 'Costos duros de construcción ($8,000-15,000/m²)', typical_pct: 50, typical_range_mxn: [15000000, 60000000] },
        { category: 'construction', subcategory: 'urbanization', description_en: 'Urbanization & infrastructure', description_es: 'Urbanización e infraestructura', typical_pct: 8, typical_range_mxn: [2000000, 10000000] },
        { category: 'permits', subcategory: 'land_use', description_en: 'Land use permit (Uso de Suelo)', description_es: 'Permiso de uso de suelo', typical_pct: null, typical_range_mxn: [50000, 300000] },
        { category: 'permits', subcategory: 'construction_license', description_en: 'Construction license (Licencia de Construcción)', description_es: 'Licencia de construcción', typical_pct: null, typical_range_mxn: [100000, 500000] },
        { category: 'permits', subcategory: 'environmental', description_en: 'Environmental impact assessment', description_es: 'Dictamen de impacto ambiental', typical_pct: null, typical_range_mxn: [80000, 250000] },
        { category: 'fees', subcategory: 'architect', description_en: 'Architectural design (3-6% of construction)', description_es: 'Diseño arquitectónico (3-6% de construcción)', typical_pct: 4, typical_range_mxn: [600000, 3600000] },
        { category: 'fees', subcategory: 'engineering', description_en: 'Structural & MEP engineering', description_es: 'Ingeniería estructural y MEP', typical_pct: 2, typical_range_mxn: [300000, 1800000] },
        { category: 'fees', subcategory: 'legal', description_en: 'Legal fees', description_es: 'Honorarios legales', typical_pct: 1, typical_range_mxn: [150000, 600000] },
        { category: 'financing', subcategory: 'interest', description_en: 'Construction financing (10-14% annual)', description_es: 'Financiamiento de construcción (10-14% anual)', typical_pct: 6, typical_range_mxn: [1500000, 8000000] },
        { category: 'taxes', subcategory: 'iva', description_en: 'IVA on construction (16%)', description_es: 'IVA en construcción (16%)', typical_pct: 8, typical_range_mxn: [2400000, 9600000] },
        { category: 'other', subcategory: 'marketing', description_en: 'Sales & marketing (2-4%)', description_es: 'Ventas y mercadotecnia (2-4%)', typical_pct: 3, typical_range_mxn: [500000, 3000000] },
      ]),
      default_assumptions: JSON.stringify({
        cap_rate_range: [0.05, 0.08],
        typical_construction_time_months: 18,
        vacancy_rate: 0.05,
        annual_appreciation: 0.06,
      }),
    },
    {
      name_en: 'Commercial Development',
      name_es: 'Desarrollo Comercial',
      project_type: 'commercial',
      description_en: 'Office buildings, retail spaces, or commercial plazas. Higher cap rates, longer construction timelines.',
      description_es: 'Edificios de oficinas, locales comerciales o plazas comerciales. Tasas de capitalización más altas, tiempos de construcción más largos.',
      default_costs: JSON.stringify([
        { category: 'land', subcategory: 'acquisition', description_en: 'Land acquisition (commercial zone)', description_es: 'Adquisición de terreno (zona comercial)', typical_pct: 15, typical_range_mxn: [10000000, 80000000] },
        { category: 'land', subcategory: 'notary', description_en: 'Notary fees', description_es: 'Gastos notariales', typical_pct: 1.5, typical_range_mxn: [500000, 6400000] },
        { category: 'taxes', subcategory: 'isai', description_en: 'ISAI (2-5%)', description_es: 'ISAI (2-5%)', typical_pct: 1, typical_range_mxn: [200000, 4000000] },
        { category: 'construction', subcategory: 'hard_costs', description_en: 'Construction ($12,000-25,000/m²)', description_es: 'Construcción ($12,000-25,000/m²)', typical_pct: 50, typical_range_mxn: [30000000, 150000000] },
        { category: 'construction', subcategory: 'parking', description_en: 'Parking structure', description_es: 'Estructura de estacionamiento', typical_pct: 5, typical_range_mxn: [3000000, 15000000] },
        { category: 'permits', subcategory: 'land_use', description_en: 'Commercial land use permit', description_es: 'Permiso de uso de suelo comercial', typical_pct: null, typical_range_mxn: [100000, 500000] },
        { category: 'permits', subcategory: 'construction_license', description_en: 'Construction license', description_es: 'Licencia de construcción', typical_pct: null, typical_range_mxn: [200000, 800000] },
        { category: 'permits', subcategory: 'environmental', description_en: 'Environmental impact assessment', description_es: 'Dictamen de impacto ambiental', typical_pct: null, typical_range_mxn: [150000, 500000] },
        { category: 'fees', subcategory: 'architect', description_en: 'Architectural design', description_es: 'Diseño arquitectónico', typical_pct: 4, typical_range_mxn: [1200000, 6000000] },
        { category: 'fees', subcategory: 'engineering', description_en: 'Engineering', description_es: 'Ingeniería', typical_pct: 2, typical_range_mxn: [600000, 3000000] },
        { category: 'financing', subcategory: 'interest', description_en: 'Construction financing', description_es: 'Financiamiento de construcción', typical_pct: 7, typical_range_mxn: [4000000, 20000000] },
        { category: 'taxes', subcategory: 'iva', description_en: 'IVA on construction (16%)', description_es: 'IVA en construcción (16%)', typical_pct: 8, typical_range_mxn: [4800000, 24000000] },
        { category: 'other', subcategory: 'marketing', description_en: 'Leasing & marketing', description_es: 'Comercialización y mercadotecnia', typical_pct: 2, typical_range_mxn: [1000000, 5000000] },
      ]),
      default_assumptions: JSON.stringify({
        cap_rate_range: [0.07, 0.10],
        typical_construction_time_months: 24,
        vacancy_rate: 0.10,
        annual_appreciation: 0.05,
      }),
    },
    {
      name_en: 'Mixed-Use Development',
      name_es: 'Desarrollo de Uso Mixto',
      project_type: 'mixed_use',
      description_en: 'Combined residential and commercial spaces. Popular in urban areas of Mexican cities like Guadalajara, CDMX, and Monterrey.',
      description_es: 'Espacios combinados residenciales y comerciales. Popular en zonas urbanas de ciudades mexicanas como Guadalajara, CDMX y Monterrey.',
      default_costs: JSON.stringify([
        { category: 'land', subcategory: 'acquisition', description_en: 'Land acquisition (urban)', description_es: 'Adquisición de terreno (urbano)', typical_pct: 18, typical_range_mxn: [8000000, 50000000] },
        { category: 'land', subcategory: 'notary', description_en: 'Notary fees', description_es: 'Gastos notariales', typical_pct: 1.5, typical_range_mxn: [400000, 4000000] },
        { category: 'taxes', subcategory: 'isai', description_en: 'ISAI', description_es: 'ISAI', typical_pct: 1, typical_range_mxn: [160000, 2500000] },
        { category: 'construction', subcategory: 'residential', description_en: 'Residential construction', description_es: 'Construcción residencial', typical_pct: 30, typical_range_mxn: [12000000, 50000000] },
        { category: 'construction', subcategory: 'commercial', description_en: 'Commercial construction', description_es: 'Construcción comercial', typical_pct: 20, typical_range_mxn: [8000000, 40000000] },
        { category: 'construction', subcategory: 'common_areas', description_en: 'Common areas & amenities', description_es: 'Áreas comunes y amenidades', typical_pct: 5, typical_range_mxn: [2000000, 10000000] },
        { category: 'permits', subcategory: 'land_use', description_en: 'Mixed-use land use permit', description_es: 'Permiso de uso de suelo mixto', typical_pct: null, typical_range_mxn: [100000, 400000] },
        { category: 'permits', subcategory: 'construction_license', description_en: 'Construction license', description_es: 'Licencia de construcción', typical_pct: null, typical_range_mxn: [150000, 700000] },
        { category: 'fees', subcategory: 'architect', description_en: 'Architectural design', description_es: 'Diseño arquitectónico', typical_pct: 4.5, typical_range_mxn: [900000, 5000000] },
        { category: 'fees', subcategory: 'engineering', description_en: 'Engineering', description_es: 'Ingeniería', typical_pct: 2, typical_range_mxn: [400000, 2500000] },
        { category: 'financing', subcategory: 'interest', description_en: 'Construction financing', description_es: 'Financiamiento de construcción', typical_pct: 6.5, typical_range_mxn: [3000000, 15000000] },
        { category: 'taxes', subcategory: 'iva', description_en: 'IVA on construction (16%)', description_es: 'IVA en construcción (16%)', typical_pct: 8, typical_range_mxn: [3200000, 14400000] },
        { category: 'other', subcategory: 'marketing', description_en: 'Sales & marketing', description_es: 'Ventas y mercadotecnia', typical_pct: 3, typical_range_mxn: [800000, 4000000] },
      ]),
      default_assumptions: JSON.stringify({
        cap_rate_range: [0.06, 0.09],
        typical_construction_time_months: 22,
        vacancy_rate: 0.08,
        annual_appreciation: 0.055,
      }),
    },
    {
      name_en: 'Agricultural Development',
      name_es: 'Desarrollo Agrícola',
      project_type: 'agricultural',
      description_en: 'Agricultural land development including greenhouses, processing facilities, or agro-tourism projects.',
      description_es: 'Desarrollo de terrenos agrícolas incluyendo invernaderos, plantas de procesamiento o proyectos de agroturismo.',
      default_costs: JSON.stringify([
        { category: 'land', subcategory: 'acquisition', description_en: 'Agricultural land acquisition', description_es: 'Adquisición de terreno agrícola', typical_pct: 25, typical_range_mxn: [2000000, 20000000] },
        { category: 'land', subcategory: 'notary', description_en: 'Notary fees', description_es: 'Gastos notariales', typical_pct: 1.5, typical_range_mxn: [100000, 1600000] },
        { category: 'construction', subcategory: 'infrastructure', description_en: 'Infrastructure (irrigation, roads, utilities)', description_es: 'Infraestructura (riego, caminos, servicios)', typical_pct: 20, typical_range_mxn: [1500000, 12000000] },
        { category: 'construction', subcategory: 'facilities', description_en: 'Processing/storage facilities', description_es: 'Instalaciones de procesamiento/almacenamiento', typical_pct: 15, typical_range_mxn: [1000000, 10000000] },
        { category: 'construction', subcategory: 'greenhouse', description_en: 'Greenhouse/shade structures', description_es: 'Invernaderos/estructuras de sombra', typical_pct: 10, typical_range_mxn: [800000, 8000000] },
        { category: 'permits', subcategory: 'water_rights', description_en: 'Water concession (CONAGUA)', description_es: 'Concesión de agua (CONAGUA)', typical_pct: null, typical_range_mxn: [50000, 500000] },
        { category: 'permits', subcategory: 'environmental', description_en: 'Environmental permits (SEMARNAT)', description_es: 'Permisos ambientales (SEMARNAT)', typical_pct: null, typical_range_mxn: [100000, 400000] },
        { category: 'fees', subcategory: 'agronomist', description_en: 'Agronomist consulting', description_es: 'Consultoría agronómica', typical_pct: 2, typical_range_mxn: [100000, 500000] },
        { category: 'fees', subcategory: 'legal', description_en: 'Legal (ejido/land tenure verification)', description_es: 'Legal (verificación ejidal/tenencia de tierra)', typical_pct: 1.5, typical_range_mxn: [100000, 400000] },
        { category: 'financing', subcategory: 'interest', description_en: 'Agricultural credit (FIRA/Financiera Nacional)', description_es: 'Crédito agrícola (FIRA/Financiera Nacional)', typical_pct: 5, typical_range_mxn: [500000, 4000000] },
        { category: 'other', subcategory: 'equipment', description_en: 'Equipment & machinery', description_es: 'Equipo y maquinaria', typical_pct: 10, typical_range_mxn: [500000, 5000000] },
      ]),
      default_assumptions: JSON.stringify({
        cap_rate_range: [0.04, 0.07],
        typical_development_time_months: 12,
        annual_yield_pct: 0.08,
        risk_factors: ['water_availability', 'weather', 'market_prices', 'ejido_land_tenure'],
      }),
    },
  ]);
}
